name: code-quality-sonnar

on:
  workflow_call:

    inputs:
      exit_code:
        type: string
        required: false
        default: '0'
      severity:
        type: string
        required: false
        default: 'CRITICAL,HIGH,MEDIUM'
      sonnar_project_key:
        type: string
        required: true
      working_directory:
        type: string
        required: false
        default: '.'
      sonnar_template_path:
        type: string
        required: false
        default: "@template/sonarqube.tpl"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup trivy bin 
      shell: bash
      run: |  
        wget https://github.com/aquasecurity/trivy/releases/download/v0.31.3/trivy_0.31.3_Linux-64bit.tar.gz
        tar -xvf trivy_0.31.3_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/trivy

    - name: Generate results to Pull Request comments
      id: trivy-scan
      run: |
        trivy fs --ignore-unfixed --vuln-type  os,library --security-checks vuln --exit-code ${{ inputs.exit_code }} --severity ${{ inputs.severity }} --no-progress --format template --template ${{inputs.sonnar_template_path}} -o ${{ github.event.repository.name }}-report.json ${{ inputs.working_directory }}
      continue-on-error: true

    - name: debug
      run: |
        ls -lha && cat ${{ github.event.repository.name }}-report.json
      continue-on-error: true

    - name: lendo report
      run: |
        cat ${{ github.event.repository.name }}-report.json
      continue-on-error: true

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ${{ github.workspace }}
        args: >
          -Dsonar.organization=${{ github.repository_owner }}
          -Dsonar.projectKey=${{ inputs.sonnar_project_key }}
          -Dsonar.externalIssuesReportPaths=${{ github.workspace }}/${{ github.event.repository.name }}-report.json