name: code-quality-sonnar

on:
  workflow_call:

    inputs:
      exit_code:
        type: string
        required: false
        default: '0'
      severity:
        type: string
        required: false
        default: 'CRITICAL,HIGH,MEDIUM'
      sonnar_project_key:
        type: string
        required: true
      working_directory:
        type: string
        required: false
        default: '.'
      sonnar_template_path:
        type: string
        required: false
        default: "@template/sonarqube.tpl"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build the Docker image
        run: docker build . --file ${{ inputs.dockerfile_path }} --tag ${{ inputs.app_name }}:${{ steps.vars.outputs.sha_short }}
          
      - name: Setup trivy bin 
        shell: bash
        run: |  
          wget https://github.com/aquasecurity/trivy/releases/download/v0.31.3/trivy_0.31.3_Linux-64bit.tar.gz
          tar -xvf trivy_0.31.3_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/trivy

    - name: Generate results to Pull Request comments
      id: trivy-scan
      run: |
        trivy image --ignore-unfixed --exit-code ${{ inputs.exit_code }} --severity ${{ inputs.severity }} --no-progress --format template --template ${{inputs.sonnar_template_path}} -o ${{ github.event.repository.name }}-report.json ${{ inputs.app_name }}:${{ steps.vars.outputs.sha_short }}
      continue-on-error: true

    - name: lendo report
      run: |
        pwd && cat ${{ github.event.repository.name }}-report.json
      continue-on-error: true

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ${{ github.workspace }}
        args: >
          -Dsonar.organization=${{ github.repository_owner }}
          -Dsonar.projectKey=${{ inputs.sonnar_project_key }}
          -Dsonar.externalIssuesReportPaths=${{ github.event.repository.name }}-report.json