name: secret-scanning

on:
  workflow_call:

    inputs:
      image:
        type: string
        required: false
        default: 'zricethezav/gitleaks:latest'
      exit_code:
        type: string
        required: false
        default: '0'
        
jobs:
  secret-scanning:
    name: Secret Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: git head
        run: |
          echo "My current SHA is ${{ github.event.pull_request.head.sha }}" 
          echo "My current SHA is $GITHUB_SHA" 

      - name: Run Gitleaks with Action
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          report_format: "sarif"
          fail: '${{ inputs.exit_code }}'


      - name: Run Gitleaks
        id: gitleaks-scan
        shell: bash
        run: |
          set -o pipefail
          TEMP_FILE=$(mktemp)
          docker run -v $GITHUB_WORKSPACE:/path ${{ inputs.image }} --source="/path" detect --log-level info --redact --verbose --exit-code ${{ inputs.exit_code }} --no-banner --log-opts "--no-merges"| tee $TEMP_FILE
          echo "Counting $TEMP_FILE bytes"
          BYTE_COUNT=$(wc -c < $TEMP_FILE)
          echo "Bytes: $BYTE_COUNT"
          echo "------------------------------------------------------------------------"
          echo "Byte limit for Github Pull Request comment: 50000"
          if (( $BYTE_COUNT < 50000 )); then
            echo "::set-output name=logs::$(cat $TEMP_FILE | base64 | tr -d '\n')"
            exit 0
          fi
            
          echo "Skipping Pull Request Gitleaks comment"
          RESULT="*Gitleaks scan is over character threshold, please check https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "::set-output name=logs::$(echo $RESULT | base64 | tr -d '\n')"
        continue-on-error: true

      - name: Update Pull Request with Results
        id: update-pr
        if: steps.gitleaks-scan.outputs.logs != ''
        uses: actions/github-script@v6
        env:
          GL_RESULT_BASE64: ${{ steps.gitleaks-scan.outputs.logs }}
        with:
          result-encoding: string
          script: |
            const prCommentGl = async ({github, context}) => {
              const base64String = process.env.GL_RESULT_BASE64 || "Cg=="
              const buff = Buffer.from(base64String, 'base64')
              const GlResultFormatted = buff.toString('utf-8')
                
              const prOutput = `
            <details><summary><strong>Gitleaks Results</strong></summary>

            \`\`\`bash\n
            ${GlResultFormatted}
            \`\`\`

            </details>`;

              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: prOutput
              }); 
            }
            await prCommentGl({github, context, core})
        continue-on-error: true

      - name: Gitleaks Slack Notification
        if: steps.gitleaks-scan.outputs.logs != ''
        uses: igordevopslabs/custom-actions-app/trivy-send-slack-notification@main
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ inputs.tag }}
          scan_type: 'secret scanning'