name: trivy-iac-scan

on:
  workflow_call:

    inputs:
      application_name:
        type: string
        required: false

jobs:
  secret-scanning:
    name: Secret Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: ${{ github.head_ref }}

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json"

