name: k8s-security-config-scan

on:
  workflow_call:

    inputs:
      helmfile_dir:
        type: string
        required: true
        default: 'deploy/helmfile.yaml'
      env:
        type: string
        required: true
        default: 'labs'
      scan_score:
        type: number
        description: 'A score to set exit-code 1 and break the pipeline execution'
        required: false
        default: 50

jobs:
  k8s-security-config-scan:
    name: k8s-security-config-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3  

      - name: Install Helm
        shell: bash
        run: |  
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      
      - name: Install Helm Plugins
        shell: bash
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.1
          helm plugin install https://github.com/aslafy-z/helm-git --version 0.10.0
      
      - name: Install Helmfile
        shell: bash
        run: |  
          wget https://github.com/roboll/helmfile/releases/download/v0.143.5/helmfile_linux_386
          chmod +x helmfile_linux_386
          sudo mv helmfile_linux_386 /usr/local/bin/helmfile

      - name: Install Polaris 
        shell: bash
        run: |  
          wget https://github.com/FairwindsOps/polaris/releases/download/7.0.1/polaris_linux_amd64.tar.gz
          tar -xvf polaris_linux_amd64.tar.gz
          sudo mv polaris /usr/local/bin/polaris
          

      - name: Generate k8s-security summary report
        shell: bash
        run: |  
          helmfile -f ${{inputs.helmfile_dir}} -e ${{inputs.env}} template >> deploy.yaml && polaris audit --audit-path deploy.yaml --format=pretty --only-show-failed-tests --set-exit-code-below-score ${{inputs.scan_score}}