name: secret-scanning-v2

on:
  workflow_call:
        
jobs:
  secret-scanning:
    name: Secret Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Seecret Scanning
        uses: igordevopslabs/secret-scanning-action@0.1.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ inputs.tag }}
          slack_channel: 'C03AJMEUN4W'
