name: terraform-validation

on:
  workflow_call:

    inputs:
      exit-code:
        type: string
        required: false
        default: '0'
      severity:
        type: string
        required: false
        default: 'CRITICAL,HIGH,MEDIUM'

jobs:
  modules-matrix:
    name: set-matrix
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"

      - id: set-matrix
        uses: actions/github-script@v6
        with:
          script: |
            const path = require('path');
            const modified_files = ${{ steps.files.outputs.added_modified }}
            const modules = Array.from(new Set(modified_files.filter((f) => path.extname(f) == '.tf').map((f) => path.dirname(f)))) || []
            console.log(`modified modules ${modules}`)
            const json = JSON.stringify({"module": modules})
            console.log(`::set-output name=matrix::${json}`)
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: modules-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.modules-matrix.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.bot_github_token }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.37.0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.bot_ssh_key }}

      - name: Configure git for private modules
        run: git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: tflint
        run: |
          tflint --init -c $(git rev-parse --show-toplevel)/.tflint.hcl
          tflint -c $(git rev-parse --show-toplevel)/.tflint.hcl .
  
  security-scan:
    name: security-scan
    runs-on: ubuntu-latest
    needs: [modules-matrix, lint]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.modules-matrix.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: ${{ matrix.module }}
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '${{ inputs.exit-code }}'
          ignore-unfixed: true
          severity: '${{ inputs.severity }}'

      - name: Generate Trivy JSON report
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: ${{ matrix.module }}
          scan-type: 'config'
          hide-progress: false
          format: 'json'
          output: '${{ github.event.repository.name }}-results.json'
          exit-code: '${{ inputs.exit-code }}'
          ignore-unfixed: true
          severity: '${{ inputs.severity }}'