name: trivy-iac-scan

on:
  workflow_call:

jobs:
  iac-scanning:
    name: IAC Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

      - name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: Trivy Iac Scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Generate Trivy JSON report
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'json'
          output: '${{ github.event.repository.name }}-results.json'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Get the output from the trivy step
        run: |
          RESULT=$(cat ${{ github.event.repository.name }}-results.json | jq  '.Results[].MisconfSummary.Failures')
          if [[ "$RESULT" != 0 ]]; then
            echo "### Ops, parece que temos alguns  pontos a serem corrigidos. Dê uma olhada no step Trivy Iac Scanning. :rotating_light:" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Show! nenhum problema encontrado nos arquivos de declaração da infraestrutura :green_heart:" >> $GITHUB_STEP_SUMMARY
          fi