name: trivy-deps-scan

on:
  workflow_call:

    inputs:
      skip_file:
        type: string
        required: false
        default: 'gitleaks-report.sarif'
      working_directory:
        type: string
        required: false
        default: '.'
      exit_code:
        type: string
        required: false
        default: '0'
      severity:
        type: string
        required: false
        default: 'CRITICAL,HIGH'
      loki_url_api:
        type: string
        required: false
        default: 'http://loki.shared.stone.credit/loki/api/v1/push'


jobs:
  fs-scanning:
    name: Repo external deps Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Setup trivy bin  
        shell: bash
        run: |  
          wget https://github.com/aquasecurity/trivy/releases/download/v0.31.3/trivy_0.31.3_Linux-64bit.tar.gz
          tar -xvf trivy_0.31.3_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/trivy

      - name: Generate results to Pull Request comments
        env:
          SEVERITY: ${{ inputs.severity }}
          EXIT_CODE: ${{inputs.exit_code}}
          APP: ${{ inputs.app_name }}
          SKIP_FILE: ${{ inputs.skip_file }}
          WORKING_DIR: ${{ inputs.working_directory }}
        id: trivy-scan
        run: |
          set -o pipefail
          TEMP_FILE=$(mktemp)
          trivy fs  --format table --exit-code $EXIT_CODE --ignore-unfixed --vuln-type os,library --security-checks vuln --severity $SEVERITY --timeout  2m0s --no-progress --skip-files $SKIP_FILE $WORKING_DIR | tee $TEMP_FILE
          echo "Counting $TEMP_FILE bytes"
          BYTE_COUNT=$(wc -c < $TEMP_FILE)
          echo "Bytes: $BYTE_COUNT"
          echo "------------------------------------------------------------------------"
          echo "Byte limit for Github Pull Request comment: 50000"
          if (( $BYTE_COUNT < 50000 )); then
            echo "logs=$(cat $TEMP_FILE | base64 | tr -d '\n')" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Skipping Pull Request Trivy Scan comment"
          RESULT="*Trivy external deps scan is over character threshold, please check https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "logs=$(echo $RESULT | base64 | tr -d '\n')" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Update Pull Request with Vulnerable report
        if: steps.trivy-scan.outputs.logs != ''
        uses: actions/github-script@v6
        env:
          TRIVY_RESULT_BASE64: ${{ steps.trivy-scan.outputs.logs }}
        with:
          result-encoding: string
          script: |
            const prCommentTrivy = async ({github, context}) => {
              const base64String = process.env.TRIVY_RESULT_BASE64 || "Cg=="
              const buff = Buffer.from(base64String, 'base64')
              const trivyResultFormatted = buff.toString('utf-8')
              
              const prOutput = `
            <summary><strong>:poop: :radioactive: :rotating_light: STOP!! You have vulnerabilities with your libraries/dependencies, please fix them. :poop: :radioactive: :rotating_light: </strong></summary>

            \`\`\`bash\n
            #Library/Dependencies Security Scan Report:\n
            ${trivyResultFormatted}
            \`\`\`

            `;

              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: prOutput
              }); 
            }
            await prCommentTrivy({github, context, core})
        continue-on-error: true
        
      - name: Update Pull Request with Success Report
        if: steps.trivy-scan.outputs.logs == '' 
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const prCommentTrivy = async ({github, context}) => {              
              const prOutput = `
            <summary><strong>:1st_place_medal: No security issues was found!!! :beginner: </strong></summary>

            \`\`\`bash\n
            #Library/Dependencies Security Scan Report\n
            NO VULNERABILITY FOUND.
            \`\`\`

            `;

              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: prOutput
              }); 
            }
            await prCommentTrivy({github, context, core})
        continue-on-error: true

      - name: Trivy Slack Notification
        if: steps.trivy-scan.outputs.logs != ''
        uses: igordevopslabs/custom-actions-app/trivy-send-slack-notification@main
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ inputs.tag }}
          scan_type: 'trivy fs'    
