name: trivy-fs-scan

on:
  workflow_call:

    inputs:
      skipp_file:
        type: string
        required: true

jobs:
  fs-scanning:
    name: Repo File System Scanning 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v3

      - name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

      - name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: Run Trivy vulnerability scanner filesystem mode
        id: trivyfs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          hide-progress: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          security-checks: 'secret,vuln'
          timeout: '2m0s'
          skip-files: '${{ inputs.skipp_file }}'

      - name: Generate Trivy JSON report
        id: trivyreport
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: true
          format: 'json'
          output: '${{ github.event.repository.name }}-results.json'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Get the output from the trivy step
        run: |
          cat ${{ github.event.repository.name }}-results.json | jq  '.Results[].MisconfSummary.Failures'
          echo "Trivy Summary: ${{ steps.trivyreport.outputs.output }}" >> $GITHUB_STEP_SUMMARY
